development:
  host: localhost
  template: template0
  encoding: utf8
  adapter: postgresql
  database: loanittome_development
  pool: 5
  timeout: 5000

test:
  host: localhost
  template: template0
  encoding: utf8
  adapter: postgresql
  database: loanittome_test
  pool: 5
  timeout: 5000

production:
  host: localhost
  template: template0
  encoding: utf8
  adapter: postgresql
  database: loanittome_production
  pool: 5
  timeout: 5000
